### ISSUE TITLE
Error after inserting the Sendy endpoint and List ID in admin

### ISSUE THREAD

**Issue by hamaso** [purplebeanie/ocsendyintegration#1]
Hi,

I've been searching around on extension that integrates between Opencart registration and Sendy, and I found yours. Thank you for your effort on this extension.

I'm currently using Opencart 1.5.6 with VQmod 2.4.1. After uploading all the files to my test site and giving permission for the admin user group to access the Opencart Sendy integration interface, I inserted the Sendy endpoint URL and list ID.
## But unfortunately after clicking the Save button, I've got this error page

Forbidden
You don't have permission to access /admin/index.php on this server.
## Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

The default file permission for admin/index.php is 644, and changing that to other values does not fix the problem.

Do you know why this is happening?

Thank you for your response.

**Comment by purplebeanie** [comment]
Hi Hamaso,

You most likely also need to give the user group modify permissions to the extension/ocsendyintegration.

It needs both access and modify to function correctly.

Cheers,
Eric.

**Comment by hamaso** [comment]
Hi Purplebeanie,

Thank you for your feedback. Actually I already set that up, but still the result is the same :(

I installed this extension on a fresh Opencart 1.5.6 installation with VQmod 2.4.1 installed, no other extensions installed just to be sure if other extension might have conflict with it.

Do you know of any other reason?

Thank you.

**Comment by purplebeanie** [comment]
Probably the only other thing that's generated Forbidden errors is mod_security particularly when passing a url as part of a POST request.

You could either disable mod_security if it's enabled or probably easier is use phpmyadmin to update the sendy end point directly in the zd1_setting table.  where zd1 is replaced with your database prefix.

You will find the sendy end point in the zd1_setting table defined as group ocsendyintegration and key is sendy_endpoint.  Just change to full domain name with http:// or https:// as required.

Eric.

**Comment by hamaso** [comment]
I don't have access to disable the mod_security, so it seems altering the database using phpmyadmin directly as you suggest maybe the way to go.

However, I can only see the oc_ocsendyintegration table in the database. I do not see the group ocsendyintegration in the oc_setting as you mentioned.

**Comment by purplebeanie** [comment]
Argh that'd be right your settings haven't been created because it's never done a successful save!

Okay so there's two settings you need in the settings table:

for both of them these settings would all be the same:

store_id = 0 or whatever store_id it is attached to (in most cases 0)
group = ocsendyintegration
serialized = 0

the only things that would change is:

key = sendy_endpoint (your endpoint)
key = sendy_list_id (your list id as reported by sendy)

These are both plain text.  So you'll just be able to add a new row in phpmyadmin the setting_id should be populate automatically it's the PK.

Eric.

**Comment by hamaso** [comment]
Hey, it works! :+1: 

Thank you thank you thank you very much for your assistance :)
Now I can easily use Sendy as my main newsletter sending platform, knowing that all my new customers who subscribe the newsletter will automatically be synced with the customers list in Sendy.

Do you have plan to expand the functionality of this excellent Opencart extension even further? It would be a good opportunity because right now I don't find any yet when it comes to integration between Sendy and Opencart.

Just an idea. What I have in mind is, when a visitor visits the website, he may want to subscribe to the "subscribers list". Then after a series of drip campaign emails, he may want to register as a member, which drop him from the "subscribers list" and automatically subscribe him to the "members list". When he makes a purchase, the system will again automatically unsubscribe him from the "members list" and subscribe him into the "buyers list". I bet this is the best way to lure a website visitor to our Opencart store to buy products, and encourage existing customers to buy even more products. Because each list is tailored with a different email campaign with a different message.

I've been reading the Sendy API documentation but because I'm not a programmer, it was of no help to me. LOL.

**Comment by purplebeanie** [comment]
Awesome thanks for letting me know.

Yes I do intend to extend it but I've just been swamped with some other projects so this has sort of been put on the back burner since about september last year..... unfortunately! 

It needs some focus to get it where I really want to which includes adding auto responders on different purchasing options, anniversary dates of purchases etc.

Unfortunately I've been a little limited with time.

Cheers,
Eric.

**Comment by milezzz** [comment]
Just chiming in to say I would gladly pay for this plugin!

**Comment by purplebeanie** [comment]
Hey @milezteg, thanks for the comment.  Sadly I switched off the last of our open cart servers about in November 2014 so it's unfortunately now a platform I no longer use, which is sort of a shame because it was a good platform. 

Either way I think this plugin would need a bit of a freshen up to work with OpenCart 2.  You're quite welcome to fork it if you want.  With no more OC installs, I don't really have the capacity to develop / support something I no longer use on a daily basis.

Eric.
